import type { Implementation } from '../../api/generated';
import { DB_TYPE } from '../database/config';
import { getDatabase } from '../database/client';

import { InMemoryUserRepository } from '../repository/memory/in-memory-user.repository';
import { PostgresUserRepository } from '../repository/postgres/postgres-user.repository';
import { InMemoryAdminRepository } from '../repository/memory/in-memory-admin.repository';
import { PostgresAdminRepository } from '../repository/postgres/postgres-admin.repository';
import { InMemorySubscriptionRepository } from '../repository/memory/in-memory-subscription.repository';
import { PostgresSubscriptionRepository } from '../repository/postgres/postgres-subscription.repository';
import { InMemoryInvoiceRepository } from '../repository/memory/in-memory-invoice.repository';
import { PostgresInvoiceRepository } from '../repository/postgres/postgres-invoice.repository';

import type { UserRepository } from '../repository/user.repository';
import type { AdminRepository } from '../repository/admin.repository';
import type { SubscriptionRepository } from '../repository/subscription.repository';
import type { InvoiceRepository } from '../repository/invoice.repository';

import { createAuthHandlers } from './public/auth';
import { createRegistrationHandlers } from './public/registration';
import { createSubscriptionHandlers } from './authenticated/subscription';
import { createUserHandlers } from './admin/user';
import { createAdminAuthHandlers } from './admin/auth';
import { createBillingHandlers } from './admin/billing';
import { createReportHandlers } from './admin/report';
import { createInvoiceHandlers } from './admin/invoice';

import { UserService } from '../service/user.service';
import { BillingService } from '../service/billing.service';
import { ReportService } from '../service/report.service';
import { SubscriptionService } from '../service/subscription.service';
import { AuthService } from '../service/auth.service';
import { InvoiceService } from '../service/invoice.service';

const databaseInstance = getDatabase();
let userRepository: UserRepository;
let adminRepository: AdminRepository;
let subscriptionRepository: SubscriptionRepository;
let invoiceRepository: InvoiceRepository;

if (DB_TYPE === 'postgres') {
    userRepository = new PostgresUserRepository(databaseInstance);
    adminRepository = new PostgresAdminRepository(databaseInstance);
    subscriptionRepository = new PostgresSubscriptionRepository(databaseInstance);
    invoiceRepository = new PostgresInvoiceRepository(databaseInstance);
} else {
    userRepository = new InMemoryUserRepository(databaseInstance);
    adminRepository = new InMemoryAdminRepository(databaseInstance);
    subscriptionRepository = new InMemorySubscriptionRepository(databaseInstance);
    invoiceRepository = new InMemoryInvoiceRepository(databaseInstance);
}

// Services
const billingService = new BillingService(invoiceRepository, subscriptionRepository, userRepository);
const reportingService = new ReportService(invoiceRepository, userRepository);
const subscriptionService = new SubscriptionService(subscriptionRepository, userRepository);
const authService = new AuthService(userRepository, adminRepository);
const userService = new UserService(userRepository);
const invoiceService = new InvoiceService(invoiceRepository, subscriptionRepository, userRepository);

// Concrete Handlers
const authHandlers = createAuthHandlers(authService);
const registrationHandlers = createRegistrationHandlers(userService);
const userHandlers = createUserHandlers(userService);
const adminAuthHandlers = createAdminAuthHandlers(authService);
const subscriptionHandlers = createSubscriptionHandlers(subscriptionService);
const billingHandlers = createBillingHandlers(billingService);
const reportHandlers = createReportHandlers(reportingService);
const invoiceHandlers = createInvoiceHandlers(invoiceService);

/**
 * The handlers object based on the Implementation interface generated by the OpenAPI generator
 */
export const handlers: Implementation = {
    // PUBLIC
    login: authHandlers.login,
    adminLogin: adminAuthHandlers.adminLogin,
    createUser: registrationHandlers.createUser,

    // AUTHENTICATED USER
    listSubscriptions: subscriptionHandlers.listSubscriptions,
    createSubscription: subscriptionHandlers.createSubscription,
    getSubscription: subscriptionHandlers.getSubscription,
    updateSubscription: subscriptionHandlers.updateSubscription,
    cancelSubscription: subscriptionHandlers.cancelSubscription,

    // ADMIN
    listUsers: userHandlers.listUsers,
    getUser: userHandlers.getUser,
    updateUser: userHandlers.updateUser,
    deleteUser: userHandlers.deleteUser,
    updateUserStatus: userHandlers.updateUserStatus,
    updatePaymentStatus: billingHandlers.updatePaymentStatus,
    generateMonthlyBilling: billingHandlers.generateMonthlyBilling,
    exportDirectDebits: reportHandlers.exportDirectDebits,
    getMonthlyRevenue: reportHandlers.getMonthlyRevenue,
    listInvoices: invoiceHandlers.listInvoices,
};
