/**
 * Backoffice Abonnés - Groupe 2
 * API BACK de gestion des joueurs abonnés. - Gestion des utilisateurs et abonnements - Transmission des facturations au Groupe 3 - Transmission des prélèvements au Groupe 4 - Mise à jour des statuts joueurs, chiffre d’affaires et règlements Hypothèse : abonnements mensuels complets, pas de prorata journalier. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Ligne d\'export comptable pour le Groupe 3.
*/
export class AccountingExportLine {
    'date'?: string;
    'generalAccount'?: string;
    'clientAccount'?: string;
    'description'?: string;
    'invoiceRef'?: string;
    'debit'?: number;
    'credit'?: number;
    'customerName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "generalAccount",
            "baseName": "generalAccount",
            "type": "string"
        },
        {
            "name": "clientAccount",
            "baseName": "clientAccount",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "invoiceRef",
            "baseName": "invoiceRef",
            "type": "string"
        },
        {
            "name": "debit",
            "baseName": "debit",
            "type": "number"
        },
        {
            "name": "credit",
            "baseName": "credit",
            "type": "number"
        },
        {
            "name": "customerName",
            "baseName": "customerName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountingExportLine.attributeTypeMap;
    }
}

