/**
 * Backoffice Abonnés - Groupe 2
 * API BACK de gestion des joueurs abonnés. - Gestion des utilisateurs et abonnements - Transmission des facturations au Groupe 3 - Transmission des prélèvements au Groupe 4 - Mise à jour des statuts joueurs, chiffre d’affaires et règlements Hypothèse : abonnements mensuels complets, pas de prorata journalier. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodType } from './paymentMethodType';

/**
* Ordre de prélèvement à envoyer au Groupe 4.
*/
export class DirectDebitOrder {
    'id'?: string;
    'invoiceId'?: string;
    'userId'?: string;
    'executionDate'?: string;
    'amount'?: number;
    'status'?: DirectDebitOrder.StatusEnum;
    'paymentMethod'?: PaymentMethodType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "executionDate",
            "baseName": "executionDate",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DirectDebitOrder.StatusEnum"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "PaymentMethodType"
        }    ];

    static getAttributeTypeMap() {
        return DirectDebitOrder.attributeTypeMap;
    }
}

export namespace DirectDebitOrder {
    export enum StatusEnum {
        ToSend = <any> 'TO_SEND',
        Sent = <any> 'SENT',
        Executed = <any> 'EXECUTED',
        Rejected = <any> 'REJECTED'
    }
}
