/**
 * Backoffice Abonnés - Groupe 2
 * API BACK de gestion des joueurs abonnés. - Gestion des utilisateurs et abonnements - Transmission des facturations au Groupe 3 - Transmission des prélèvements au Groupe 4 - Mise à jour des statuts joueurs, chiffre d’affaires et règlements Hypothèse : abonnements mensuels complets, pas de prorata journalier. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Invoice {
    'id'?: string;
    'userId'?: string;
    'subscriptionId'?: string;
    'invoiceRef'?: string;
    'periodStart'?: string;
    'periodEnd'?: string;
    /**
    * Dernier jour du mois de facturation.
    */
    'billingDate'?: string;
    'amountExclVat'?: number;
    'vatAmount'?: number;
    'amountInclVat'?: number;
    'status'?: Invoice.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "subscriptionId",
            "baseName": "subscriptionId",
            "type": "string"
        },
        {
            "name": "invoiceRef",
            "baseName": "invoiceRef",
            "type": "string"
        },
        {
            "name": "periodStart",
            "baseName": "periodStart",
            "type": "string"
        },
        {
            "name": "periodEnd",
            "baseName": "periodEnd",
            "type": "string"
        },
        {
            "name": "billingDate",
            "baseName": "billingDate",
            "type": "string"
        },
        {
            "name": "amountExclVat",
            "baseName": "amountExclVat",
            "type": "number"
        },
        {
            "name": "vatAmount",
            "baseName": "vatAmount",
            "type": "number"
        },
        {
            "name": "amountInclVat",
            "baseName": "amountInclVat",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Invoice.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return Invoice.attributeTypeMap;
    }
}

export namespace Invoice {
    export enum StatusEnum {
        Pending = <any> 'PENDING',
        Sent = <any> 'SENT',
        Paid = <any> 'PAID',
        Failed = <any> 'FAILED'
    }
}
