/**
 * Backoffice Abonnés - Groupe 2
 * API BACK de gestion des joueurs abonnés. - Gestion des utilisateurs et abonnements - Transmission des facturations au Groupe 3 - Transmission des prélèvements au Groupe 4 - Mise à jour des statuts joueurs, chiffre d’affaires et règlements Hypothèse : abonnements mensuels complets, pas de prorata journalier. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethodType } from './paymentMethodType';

export class PaymentMethod {
    'type'?: PaymentMethodType;
    /**
    * IBAN masqué pour SEPA.
    */
    'iban'?: string;
    /**
    * 4 derniers chiffres pour CB.
    */
    'cardLast4'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentMethodType"
        },
        {
            "name": "iban",
            "baseName": "iban",
            "type": "string"
        },
        {
            "name": "cardLast4",
            "baseName": "cardLast4",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentMethod.attributeTypeMap;
    }
}

export namespace PaymentMethod {
}
