/**
 * Backoffice Abonnés - Groupe 2
 * API BACK de gestion des joueurs abonnés. - Gestion des utilisateurs et abonnements - Transmission des facturations au Groupe 3 - Transmission des prélèvements au Groupe 4 - Mise à jour des statuts joueurs, chiffre d’affaires et règlements Hypothèse : abonnements mensuels complets, pas de prorata journalier. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Statut d\'accès du joueur. OK = accès plateforme autorisé. 
*/
export enum UserStatus {
    Ok = <any> 'OK',
    Suspended = <any> 'SUSPENDED',
    Bloque = <any> 'BLOQUE',
    Deleted = <any> 'DELETED'
}
