/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import { z } from "zod/v4"

export const s_AccountingExportLine = z.object({
  date: z.string().optional(),
  generalAccount: z.string().optional(),
  clientAccount: z.string().optional(),
  description: z.string().optional(),
  invoiceRef: z.string().optional(),
  debit: z.coerce.number().nullable().optional(),
  credit: z.coerce.number().nullable().optional(),
  customerName: z.string().optional(),
})

export const s_Invoice = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  subscriptionId: z.string().optional(),
  invoiceRef: z.string().optional(),
  periodStart: z.string().optional(),
  periodEnd: z.string().optional(),
  billingDate: z.string().optional(),
  amountExclVat: z.coerce.number().optional(),
  vatAmount: z.coerce.number().optional(),
  amountInclVat: z.coerce.number().optional(),
  status: z.enum(["PENDING", "SENT", "PAID", "FAILED"]).optional(),
})

export const s_PaymentMethodType = z.enum(["SEPA", "CARD"])

export const s_SubscriptionCreate = z.object({
  userId: z.string(),
  contractCode: z.string(),
  startDate: z.string(),
  monthlyAmount: z.coerce.number(),
  promoCode: z.string().nullable().optional(),
})

export const s_SubscriptionStatus = z.enum([
  "ACTIVE",
  "CANCELLED",
  "PENDING_CANCEL",
])

export const s_UserStatus = z.enum(["OK", "SUSPENDED", "BLOQUE", "DELETED"])

export const s_DirectDebitOrder = z.object({
  id: z.string().optional(),
  invoiceId: z.string().optional(),
  userId: z.string().optional(),
  executionDate: z.string().optional(),
  amount: z.coerce.number().optional(),
  status: z.enum(["TO_SEND", "SENT", "EXECUTED", "REJECTED"]).optional(),
  paymentMethod: s_PaymentMethodType.optional(),
})

export const s_PaymentMethod = z.object({
  type: s_PaymentMethodType.optional(),
  iban: z.string().optional(),
  cardLast4: z.string().optional(),
})

export const s_Subscription = z.object({
  id: z.string().optional(),
  userId: z.string().optional(),
  contractCode: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().nullable().optional(),
  monthlyAmount: z.coerce.number().optional(),
  promoCode: z.string().nullable().optional(),
  status: s_SubscriptionStatus.optional(),
})

export const s_SubscriptionUpdate = z.object({
  endDate: z.string().nullable().optional(),
  monthlyAmount: z.coerce.number().optional(),
  promoCode: z.string().nullable().optional(),
  status: s_SubscriptionStatus.optional(),
})

export const s_User = z.object({
  id: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.email().optional(),
  status: s_UserStatus.optional(),
  paymentMethod: s_PaymentMethod.optional(),
  createdAt: z.iso.datetime({ offset: true }).optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
})

export const s_UserCreate = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.email(),
  paymentMethod: s_PaymentMethod.optional(),
})

export const s_UserUpdate = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.email().optional(),
  status: s_UserStatus.optional(),
  paymentMethod: s_PaymentMethod.optional(),
})
